version: '3.8'

services:
  n8n:
    build: .
    env_file:
      - .env
    ports:
      - '5555:5555'
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
