name: Web Tests

on:
  push:
    paths:
      - 'apps/web/**'
    branches: [main]
  pull_request:
    paths:
      - 'apps/web/**'
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./apps/web
        run: npm install

      - name: Run tests
        working-directory: ./apps/web
        run: npm test
