name: API Build

on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/api/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'apps/api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./apps/api
        run: npm install

      - name: Build
        working-directory: ./apps/api
        run: npm run build
